version: "3.7"

services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=temper_code_test
      - MYSQL_USER=temper_code_test
      - MYSQL_PASSWORD=good_luck
#    ports:
#      - "3306:3306"
    restart: always

  python:
    image: python_Image
    build: images/Load_Data_Python
    command: ["./Load_csv_data.py"]
    volumes:
      - ./data:/data
